language: julia
notifications:
  email:
    on_success: change
    on_failure: always
codecov: true
coveralls: true
git:
  depth: false
os:
- linux
- osx
arch:
- x64
julia:
- 1.0
- 1.3
- 1.4
addons:
  apt:
    packages:
      - python-matplotlib
      - python3-matplotlib
env:
  matrix:
    - PYTHON=python
    - PYTHON=python3
    - PYTHON=Conda
matrix:
  exclude:
  - julia: 1.0
    os: linux
    env: PYTHON=Conda
before_script:
- if [ $TRAVIS_OS_NAME = osx ]; then brew install python gcc freetype pyqt; brew link --force freetype; fi
after_success:
- julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
script:
- if [ $TRAVIS_OS_NAME = osx ]; then pip install numpy scipy matplotlib; fi
- if [[ -a .git/shallow ]]; then git fetch; fi
- julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true);'
