language: julia
notifications:
  email:
    on_success: change
    on_failure: always
codecov: true
coveralls: true
os:
- linux
- osx
julia:
- 1.0
- 1.1
- nightly
addons:
  apt:
    packages:
      - python-matplotlib
      - python3-matplotlib
matrix:
    - PYTHON=python  # python 2.7
    - PYTHON=python3 # python 3.5
  allow_failures:
  - julia: nightly
after_success:
- julia -e 'VERSION >= v"0.7.0-DEV.5183" && using Pkg; VERSION >= v"0.7.0-DEV.5183"
  || cd(Pkg.dir("SeisIO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder());
  Codecov.submit(Coveralls.process_folder()); '
