language: julia
notifications:
  email:
    on_success: change
    on_failure: always
codecov: true
coveralls: true
os:
- linux
julia:
- 1.0
- 1.3
addons:
  apt:
    packages:
      - python-matplotlib
      - python3-matplotlib
env:
  matrix:
    - PYTHON=python
    - PYTHON=python3
matrix:
  allow_failures:
  - julia: nightly
after_success:
- julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
