environment:
  matrix:
  - julia_version: 1
    PYTHON: "Conda"
  - julia_version: 1.3
    PYTHON: "Conda"
  - julia_version: 1.4
    PYTHON: "Conda"
platform:
  - x64 # 64-bit only

matrix:
  allow_failures:
    - julia_version: 1.4

branches:
  only:
    - main
    - dev
notifications:
  - provider: Email
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"

on_success:
  - echo "%JL_CODECOV_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_CODECOV_SCRIPT%"
